import type { Asset, ReferenceRole, VisualReference } from "@studio/types";
import { useRef, useState } from "react";

type DraftUpload = { file: File; dataUrl: string };

export function useReferenceWorkspace() {
  const [quickReferenceUpload, setQuickReferenceUpload] = useState<DraftUpload | null>(null);
  const [quickReferenceNote, setQuickReferenceNote] = useState("");
  const [selectedReferenceId, setSelectedReferenceId] = useState<string | null>(null);
  const [referenceModalPane, setReferenceModalPane] = useState<"main" | "detail">("main");
  const [referenceProfileEditing, setReferenceProfileEditing] = useState(false);
  const [previewGeneratedAsset, setPreviewGeneratedAsset] = useState<Asset | null>(null);
  const [previewUpload, setPreviewUpload] = useState<{ title: string; dataUrl: string; note: string } | null>(null);
  const [missingImageRequest, setMissingImageRequest] = useState("");
  const [referenceRevisionOpen, setReferenceRevisionOpen] = useState(false);
  const [referenceRevisionRequest, setReferenceRevisionRequest] = useState("");
  const [pendingReferencePaneKeys, setPendingReferencePaneKeys] = useState<Set<string>>(() => new Set());
  const [previewRevisionOpen, setPreviewRevisionOpen] = useState(false);
  const [activeCharacterSlot, setActiveCharacterSlot] = useState("");
  const [candidateEdit, setCandidateEdit] = useState<Record<string, string>>({});
  const [candidateCarouselIndex, setCandidateCarouselIndex] = useState<Record<string, number>>({});
  const [referenceCandidates, setReferenceCandidates] = useState<Array<{
    id: string; name: string; dataUrl: string; mimeType: string; role: ReferenceRole;
    referenceUse: VisualReference["referenceUse"]; characterSlot: string;
    sourceDescription: string; transformationRequest: string;
  }>>([]);
  const [referenceDraft, setReferenceDraft] = useState({
    name: "", role: "main_character" as ReferenceRole,
    referenceUse: "primary_identity" as VisualReference["referenceUse"],
    visualStyle: "realistic", characterSlot: "", sourceDescription: "", transformationRequest: "",
    primaryUploads: [] as DraftUpload[], detailUploads: [] as DraftUpload[]
  });
  const primaryUploadInputRef = useRef<HTMLInputElement | null>(null);
  const detailUploadInputRef = useRef<HTMLInputElement | null>(null);
  const quickReferenceInputRef = useRef<HTMLInputElement | null>(null);
  const referenceModalUploadInputRef = useRef<HTMLInputElement | null>(null);
  const autoGeneratedEmptySlotsRef = useRef<Set<string>>(new Set());

  return {
    quickReferenceUpload, setQuickReferenceUpload, quickReferenceNote, setQuickReferenceNote,
    selectedReferenceId, setSelectedReferenceId, referenceModalPane, setReferenceModalPane,
    referenceProfileEditing, setReferenceProfileEditing, previewGeneratedAsset, setPreviewGeneratedAsset,
    previewUpload, setPreviewUpload, missingImageRequest, setMissingImageRequest,
    referenceRevisionOpen, setReferenceRevisionOpen, referenceRevisionRequest, setReferenceRevisionRequest,
    pendingReferencePaneKeys, setPendingReferencePaneKeys, previewRevisionOpen, setPreviewRevisionOpen,
    activeCharacterSlot, setActiveCharacterSlot, candidateEdit, setCandidateEdit,
    candidateCarouselIndex, setCandidateCarouselIndex, referenceCandidates, setReferenceCandidates,
    referenceDraft, setReferenceDraft, primaryUploadInputRef, detailUploadInputRef,
    quickReferenceInputRef, referenceModalUploadInputRef, autoGeneratedEmptySlotsRef
  };
}

export type ReferenceWorkspace = ReturnType<typeof useReferenceWorkspace>;
