import { createReferenceGenerationActions } from "@studio/workflow/orchestration/reference-generation-actions";
import { createReferenceActions } from "@studio/workflow/orchestration/reference-actions";
import { useStudioReferenceEffects } from "./hooks/studio-reference-effects";

type ReferenceActionArgs = Parameters<typeof createReferenceActions>[0];
type ReferenceGenerationArgs = Parameters<typeof createReferenceGenerationActions>[0];
type ReferenceEffectsArgs = Parameters<typeof useStudioReferenceEffects>[0];

export type StudioReferenceDomainArgs = Omit<ReferenceActionArgs, "flagStoryCharacterChange" | "queueCharacterImageDraft" | "updateCharacter"> & ReferenceGenerationArgs & {
  autoGeneratedEmptySlotsRef: ReferenceEffectsArgs["autoGeneratedEmptySlotsRef"];
  selectedReferenceDetailJobActive: ReferenceEffectsArgs["selectedReferenceDetailJobActive"];
  selectedReferenceSupportsDetail: ReferenceEffectsArgs["selectedReferenceSupportsDetail"];
  previewGeneratedAsset: ReferenceEffectsArgs["previewGeneratedAsset"];
  selectedReferencePaneHasImage: ReferenceEffectsArgs["selectedReferencePaneHasImage"];
  selectedReferencePaneFailedJob: ReferenceEffectsArgs["selectedReferencePaneFailedJob"];
  selectedReferencePaneLatestJob: ReferenceEffectsArgs["selectedReferencePaneLatestJob"];
  selectedReferencePaneKey: ReferenceEffectsArgs["selectedReferencePaneKey"];
  setReferenceModalPane: ReferenceEffectsArgs["setReferenceModalPane"];
  setPreviewRevisionOpen: ReferenceEffectsArgs["setPreviewRevisionOpen"];
  setReferenceRevisionOpen: ReferenceEffectsArgs["setReferenceRevisionOpen"];
  setReferenceRevisionRequest: ReferenceEffectsArgs["setReferenceRevisionRequest"];
  setMissingImageRequest: ReferenceEffectsArgs["setMissingImageRequest"];
  setPendingReferencePaneKeys: ReferenceEffectsArgs["setPendingReferencePaneKeys"];
};

export function useStudioReferenceDomain(args: StudioReferenceDomainArgs) {
  let generationActions!: ReturnType<typeof createReferenceGenerationActions>;
  const flagStoryCharacterChange = (reason: string) => generationActions.flagStoryCharacterChange(reason);
  const updateCharacter = (patch: Parameters<ReferenceActionArgs["updateCharacter"]>[0]) => generationActions.updateCharacter(patch);
  const queueCharacterImageDraft = (...values: Parameters<ReferenceEffectsArgs["queueCharacterImageDraft"]>) => generationActions.queueCharacterImageDraft(...values);
  const referenceActions = createReferenceActions({ ...args, flagStoryCharacterChange, updateCharacter, queueCharacterImageDraft });
  generationActions = createReferenceGenerationActions({ ...args, runDemoJob: args.runDemoJob });
  useStudioReferenceEffects({
    projectId: args.project.id, referenceModalPane: args.referenceModalPane, selectedReference: args.selectedReference ?? null,
    selectedReferenceDetail: args.selectedReferenceDetail, selectedReferenceDetailJobActive: args.selectedReferenceDetailJobActive,
    selectedReferenceHasGenerationData: args.selectedReferenceHasGenerationData, selectedReferenceName: args.selectedReferenceName,
    selectedReferencePrimary: args.selectedReferencePrimary, selectedReferenceRole: args.selectedReferenceRole,
    selectedReferenceSlot: args.selectedReferenceSlot, selectedReferenceSupportsDetail: args.selectedReferenceSupportsDetail,
    selectedReferencePaneHasImage: args.selectedReferencePaneHasImage, selectedReferencePaneFailedJob: args.selectedReferencePaneFailedJob,
    selectedReferencePaneLatestJob: args.selectedReferencePaneLatestJob, selectedReferencePaneKey: args.selectedReferencePaneKey,
    previewGeneratedAsset: args.previewGeneratedAsset, queueCharacterImageDraft,
    setReferenceModalPane: args.setReferenceModalPane, setPreviewRevisionOpen: args.setPreviewRevisionOpen,
    setReferenceRevisionOpen: args.setReferenceRevisionOpen, setReferenceRevisionRequest: args.setReferenceRevisionRequest,
    setMissingImageRequest: args.setMissingImageRequest, setPendingReferencePaneKeys: args.setPendingReferencePaneKeys,
    autoGeneratedEmptySlotsRef: args.autoGeneratedEmptySlotsRef
  });
  return {
    ...referenceActions,
    ...generationActions,
    flagStoryCharacterChange,
    updateCharacter,
    queueCharacterImageDraft
  };
}
