type Setter<T> = (value: T | ((current: T) => T)) => void;
type AssetShape = { id: string; projectId: string; sceneId?: string; shotId?: string; type: "image" | "video" | "audio" | "subtitle" | "reference"; filePath: string; sourceProvider: string; sourceJobId?: string; prompt?: string; width?: number; height?: number; durationSeconds?: number; metadata?: Record<string, unknown>; createdAt: string };
type ProjectShape = { id: string; name: string; description?: string; sourceDraft?: string; updatedAt: string };
type ReferenceShape = { name: string; role: string; referenceUse?: string; characterSlot?: string; sourceDescription: string; transformationRequest: string; previewDataUrl?: string };

export type UploadPreviewModel = {
  previewUpload: { title: string; dataUrl: string; note: string } | null;
  setPreviewUpload: (value: { title: string; dataUrl: string; note: string } | null) => void;
};
export type ProjectRow = { project: ProjectShape; sceneCount: number; shotCount: number; sourceCount: number; jobCount: number; actionNeededJobs: number };
export type ProjectManagerModel = {
  createProject: () => Promise<void>;
  newProjectName: string;
  project: { id: string };
  projectManagerOpen: boolean;
  projectRows: ProjectRow[];
  projectSearch: string;
  selectProject: (projectId: string) => Promise<void>;
  setAppManagerOpen: (open: boolean) => void;
  setAppManagerTab: (tab: "settings" | "projects" | "account") => void;
  setNewProjectName: (name: string) => void;
  setProjectManagerOpen: (open: boolean) => void;
  setProjectSearch: (search: string) => void;
  state: { projects: unknown[] };
};
export type GeneratedAssetPreviewModel = {
  candidateEdit: Record<string, string>;
  previewGeneratedAsset: AssetShape | null;
  previewGeneratedGroup: { key: string; name: string; slot?: string; role?: string; referenceUse?: string; assets: AssetShape[] } | undefined;
  previewGeneratedIndex: number;
  previewRevisionOpen: boolean;
  regenerateGeneratedAsset: (asset: AssetShape) => void;
  setCandidateCarouselIndex: Setter<Record<string, number>>;
  setCandidateEdit: Setter<Record<string, string>>;
  setPreviewGeneratedAsset: (asset: AssetShape | null) => void;
  setPreviewRevisionOpen: (open: boolean) => void;
};
export type AppManagerModel = {
  appManagerOpen: boolean;
  appManagerTab: "settings" | "projects" | "account";
  hasDesktopBridge?: boolean;
  bridgeCount?: number;
  bridgeVersionLabel?: string;
  bridgeStatus?: { updateRequired: boolean; expectedVersion: string; versions: string[]; connections?: Array<{ extensionId?: string; extensionInstanceId?: string; pairing?: { pairingId?: string; extensionId?: string; extensionInstanceId?: string; code?: string; state?: string; expiresAt?: number }; providerVisibility?: { googleFlowProjectTabs?: number; googleFlowCustomToolTabs?: number; googleFlowRuntimeToolTabs?: number; googleFlowEditorToolTabs?: number } }> };
  refreshBridgeStatus?: () => Promise<unknown>;
  createProject: () => Promise<void>;
  newProjectName: string;
  project: { id: string };
  projectRows: ProjectRow[];
  projectSearch: string;
  selectProject: (projectId: string) => Promise<void>;
  setAppManagerOpen: (open: boolean) => void;
  setAppManagerTab: (tab: "settings" | "projects" | "account") => void;
  setNewProjectName: (name: string) => void;
  setProjectSearch: (search: string) => void;
  state: { projects: unknown[]; jobs: Array<{ projectId?: string; providerId?: string; error?: string; statusMessage?: string }> };
};
export type ReferenceEditorModel = {
  character: { visualDescription?: string; personality?: string; consistencyNotes?: string };
  missingImageRequest: string;
  recoverJob: (jobId: string) => void;
  referenceModalPane: "main" | "detail";
  referenceModalUploadInputRef: { current: HTMLInputElement | null };
  referenceProfileEditing: boolean;
  referenceRevisionOpen: boolean;
  referenceRevisionRequest: string;
  requestMissingReferenceImage: () => void;
  requestSelectedReferenceRevision: () => void;
  selectedReference: ReferenceShape | null;
  selectedReferenceDetail: ReferenceShape | undefined;
  selectedReferenceDetailJobActive: boolean;
  selectedReferenceHasGenerationData: boolean;
  selectedReferenceMainJobActive: boolean;
  selectedReferencePaneFailedJob: { id: string; providerConversationUrl?: string } | undefined;
  selectedReferencePaneHasImage: boolean;
  selectedReferencePaneJobActive: boolean;
  selectedReferencePrimary: ReferenceShape | undefined;
  selectedReferenceSupportsDetail: boolean;
  setMissingImageRequest: (value: string) => void;
  setReferenceModalPane: Setter<"main" | "detail">;
  setReferenceProfileEditing: Setter<boolean>;
  setReferenceRevisionRequest: (value: string) => void;
  setSelectedReferenceId: (value: string | null) => void;
  state: Record<string, unknown>;
  updateCharacter: (patch: { personality?: string }) => void;
  uploadSelectedReferenceReplacement: (file: File) => Promise<void>;
};
