import { useEffect } from "react";
import type { Asset, AutomationJob, Character, VisualReference } from "@studio/types";

type ReferenceEffectsDeps = {
  projectId: string;
  referenceModalPane: "main" | "detail";
  selectedReference: VisualReference | null;
  selectedReferenceDetail?: VisualReference;
  selectedReferenceDetailJobActive: boolean;
  selectedReferenceHasGenerationData: boolean;
  selectedReferenceName: string;
  selectedReferencePrimary?: VisualReference;
  selectedReferenceRole: Character["role"];
  selectedReferenceSlot: string;
  selectedReferenceSupportsDetail: boolean;
  selectedReferencePaneHasImage: boolean;
  selectedReferencePaneFailedJob?: AutomationJob;
  selectedReferencePaneLatestJob?: AutomationJob;
  selectedReferencePaneKey: string;
  previewGeneratedAsset?: Asset | null;
  queueCharacterImageDraft: (...args: any[]) => void;
  setReferenceModalPane: (pane: "main" | "detail") => void;
  setPreviewRevisionOpen: (open: boolean) => void;
  setReferenceRevisionOpen: (open: boolean) => void;
  setReferenceRevisionRequest: (value: string) => void;
  setMissingImageRequest: (value: string) => void;
  setPendingReferencePaneKeys: (update: (current: Set<string>) => Set<string>) => void;
  autoGeneratedEmptySlotsRef: React.MutableRefObject<Set<string>>;
};

function queueMissingDetailReference(deps: ReferenceEffectsDeps): void {
  const { selectedReference, selectedReferenceSupportsDetail, referenceModalPane, selectedReferenceDetail, selectedReferenceHasGenerationData, selectedReferenceDetailJobActive, autoGeneratedEmptySlotsRef } = deps;
  if (!selectedReference || !selectedReferenceSupportsDetail || referenceModalPane !== "detail" || selectedReferenceDetail) return;
  const autoKey = `${deps.projectId}:${deps.selectedReferenceSlot}:${deps.selectedReferenceRole}:supporting_detail`;
  if (!selectedReferenceHasGenerationData || selectedReferenceDetailJobActive || autoGeneratedEmptySlotsRef.current.has(autoKey)) return;
  autoGeneratedEmptySlotsRef.current.add(autoKey);
  deps.queueCharacterImageDraft(deps.selectedReferencePrimary, "Generate the missing character detail sheet from the current locked identity. Include side views, back view, expression set, body proportions, outfit details, color palette, and concise continuity notes.", deps.selectedReferenceSlot, deps.selectedReferenceName, "supporting_detail", deps.selectedReferenceRole, "supporting_detail");
}

function clearPendingReferencePane(deps: ReferenceEffectsDeps): void {
  if (!deps.selectedReferencePaneHasImage && !deps.selectedReferencePaneFailedJob && !deps.selectedReferencePaneLatestJob) return;
  deps.setPendingReferencePaneKeys((current) => {
    if (!current.has(deps.selectedReferencePaneKey)) return current;
    const next = new Set(current);
    next.delete(deps.selectedReferencePaneKey);
    return next;
  });
}

export function useStudioReferenceEffects(deps: ReferenceEffectsDeps): void {
  const {
    projectId, referenceModalPane, selectedReference, selectedReferenceDetail,
    selectedReferenceDetailJobActive, selectedReferenceHasGenerationData, selectedReferenceName,
    selectedReferencePrimary, selectedReferenceRole, selectedReferenceSlot, selectedReferenceSupportsDetail,
    selectedReferencePaneHasImage, selectedReferencePaneFailedJob, selectedReferencePaneLatestJob,
    selectedReferencePaneKey, previewGeneratedAsset, queueCharacterImageDraft, setReferenceModalPane,
    setPreviewRevisionOpen, setReferenceRevisionOpen, setReferenceRevisionRequest, setMissingImageRequest,
    setPendingReferencePaneKeys, autoGeneratedEmptySlotsRef
  } = deps;

  useEffect(() => queueMissingDetailReference(deps), [projectId, referenceModalPane, selectedReference, selectedReferenceDetail, selectedReferenceDetailJobActive, selectedReferenceHasGenerationData, selectedReferenceName, selectedReferencePrimary, selectedReferenceRole, selectedReferenceSlot, selectedReferenceSupportsDetail, queueCharacterImageDraft]);

  useEffect(() => {
    if (selectedReference && !selectedReferenceSupportsDetail && referenceModalPane === "detail") setReferenceModalPane("main");
  }, [referenceModalPane, selectedReference, selectedReferenceSupportsDetail, setReferenceModalPane]);
  useEffect(() => setPreviewRevisionOpen(false), [previewGeneratedAsset?.id, setPreviewRevisionOpen]);
  useEffect(() => {
    setReferenceRevisionOpen(false);
    setReferenceRevisionRequest("");
    setMissingImageRequest("");
  }, [selectedReference?.id, referenceModalPane, setReferenceRevisionOpen, setReferenceRevisionRequest, setMissingImageRequest]);
  useEffect(() => clearPendingReferencePane(deps), [selectedReferencePaneFailedJob, selectedReferencePaneHasImage, selectedReferencePaneKey, selectedReferencePaneLatestJob, setPendingReferencePaneKeys]);
}
